### ISSUE TITLE
"Unable to store alias C" with ParquetStorer for PIG with Datetime fields

### ISSUE THREAD

**Issue by beeva-luisgonzalez** [Parquet/parquet-mr#450]
I think found a posible bug when using the parquet storer in pig!

When I want to save a PIG bag with ParquetStorer that has a DateTime field I always get this error.

```
================================================================================
Pig Stack Trace
---------------
ERROR 1002: Unable to store alias C

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1002: Unable to store alias C
    at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1694)
    at org.apache.pig.PigServer.registerQuery(PigServer.java:623)
    at org.apache.pig.tools.grunt.GruntParser.processPig(GruntParser.java:1061)
    at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:501)
    at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:230)
    at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:205)
    at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:66)
    at org.apache.pig.Main.run(Main.java:560)
    at org.apache.pig.Main.main(Main.java:170)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.UnsupportedOperationException
    at parquet.pig.PigSchemaConverter.convertWithName(PigSchemaConverter.java:366)
    at parquet.pig.PigSchemaConverter.convert(PigSchemaConverter.java:341)
    at parquet.pig.PigSchemaConverter.convert(PigSchemaConverter.java:378)
    at parquet.pig.PigSchemaConverter.convertTypes(PigSchemaConverter.java:334)
    at parquet.pig.PigSchemaConverter.convert(PigSchemaConverter.java:327)
    at parquet.pig.TupleWriteSupport.<init>(TupleWriteSupport.java:66)
    at parquet.pig.ParquetStorer.getOutputFormat(ParquetStorer.java:106)
    at org.apache.pig.newplan.logical.visitor.InputOutputFileValidatorVisitor.visit(InputOutputFileValidatorVisitor.java:69)
    at org.apache.pig.newplan.logical.relational.LOStore.accept(LOStore.java:66)
    at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:64)
    at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
    at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
    at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
    at org.apache.pig.newplan.DepthFirstWalker.walk(DepthFirstWalker.java:53)
    at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
    at org.apache.pig.newplan.logical.relational.LogicalPlan.validate(LogicalPlan.java:212)
    at org.apache.pig.PigServer$Graph.compile(PigServer.java:1767)
    at org.apache.pig.PigServer$Graph.access$300(PigServer.java:1443)
    at org.apache.pig.PigServer.execute(PigServer.java:1356)
    at org.apache.pig.PigServer.access$500(PigServer.java:113)
    at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1689)
    ... 14 more
================================================================================
```

The pig script I run is something like this

```
REGISTER 's3://.../emr/pig/libs/parquet-column-1.6.0.jar';
REGISTER 's3://.../emr/pig/libs/parquet-common-1.6.0.jar';
REGISTER 's3://.../emr/pig/libs/parquet-encoding-1.6.0.jar';
REGISTER 's3://.../emr/pig/libs/parquet-format-2.2.0.jar';
REGISTER 's3://.../emr/pig/libs/parquet-hadoop-1.6.0.jar';
REGISTER 's3://.../emr/pig/libs/parquet-pig-1.6.0.jar';
REGISTER 's3://.../emr/pig/libs/json_simple-1.1.jar';
REGISTER 's3://.../emr/pig/libs/elephant-bird-hadoop-compat-4.1.jar';
REGISTER 's3://.../emr/pig/libs/elephant-bird-pig-4.1.jar';

REGISTER 's3://elasticmapreduce/libs/pig/0.3/piggybank-0.3-amzn.jar';

loadJson = LOAD 's3://...../Note.json' USING com.twitter.elephantbird.pig.load.JsonLoader('-nestedLoad') AS (json:map []);
B = FOREACH loadJson GENERATE flatten(json#'data') as (m:map[]);
C = FOREACH B GENERATE m#'Id' as Id:chararray, m#'CreatedById' as CreatedById:chararray, CurrentTime() as CDR_LOAD_TIMESTAMP;

STORE C INTO 's3://.../output USING parquet.pig.ParquetStorer;
```

The error doesnt happen if I do a DUMP (instead of STORE), for me this means the problem is on the ParquetStorer but maybe I'm wrong.

The error only goes away if I transform the datetime columns to unixtimes (longs).

```
....
C = FOREACH B GENERATE m#'Id' as Id:chararray, m#'CreatedById' as CreatedById:chararray, ToUnixTime(CurrentTime()) as CDR_LOAD_TIMESTAMP;

STORE C INTO 's3://.../output USING parquet.pig.ParquetStorer;
```

My pig version:

```
[hadoop@ip-172-31-7-169 ~]$ pig --version
Apache Pig version 0.14.0-amzn-0 (r: unknown) 
compiled Nov 16 2015, 21:
```

feel free to ask me for more info or close this issue if it doesn't belong to this project!

cheers!

Luis.

**Comment by julienledem** [comment]
parquet development has moved to apache:
https://github.com/apache/parquet-mr
https://issues.apache.org/jira/browse/PARQUET
